### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by s-sajid-ali** [hepnos/HEPnOS#2]
Hi hepnos-devs, 

I'm getting the following build error when trying to build hepnos: [error-logfile](https://pastebin.com/LWXcfhFQ). The environment file explicitly sets the `cxxstd=14` variant.

Let me know if I can provide any additional information to resolve this. Thanks!

**Comment by mdorier** [comment]
Can you retry now and tell me if it works? (hepnos@main)

**Comment by s-sajid-ali** [comment]
Thanks for the prompt response and the fix! While that did fix one error, two more remain: 

- error: template parameter redefines default argument
 ```
     106     In file included from /tmp/sajid/spack-stage/spack-stage-hepnos-main-e2p2lfdjwrsvpnnrsz7doazp6kqx3slw/spack-src/src/DataStore.cpp:10:
  >> 107     /tmp/sajid/spack-stage/spack-stage-hepnos-main-e2p2lfdjwrsvpnnrsz7doazp6kqx3slw/spack-src/src/../include/hepnos/DataStore.hpp:283:35: error: template parameter redefines default argument
     108     template<typename T, typename C = std::vector<T>>
 ```
 - error: implicit instantiation of undefined template 'std::basic_stringstream<char>
 ```
   >> 113     /tmp/sajid/spack-stage/spack-stage-hepnos-main-e2p2lfdjwrsvpnnrsz7doazp6kqx3slw/spack-src/src/../include/hepnos/DataStore.hpp:304:23: error: implicit instantiation of undefined template 'std::basic_stringstream<char>'
     114         std::stringstream ss(buffer);
     115                           ^
     116     /usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/iosfwd:108:11: note: template is declared here
     117         class basic_stringstream;
 ```

**Comment by mdorier** [comment]
Which version of gcc are you using?

**Comment by mdorier** [comment]
I think I corrected the second error, but I'm puzzled by the first one. Could you give me the full log of the error also?

**Comment by s-sajid-ali** [comment]
Here's the full log file: [spack-build-out.txt](https://github.com/hepnos/HEPnOS/files/7462641/spack-build-out.txt)

The contents of the environment file (the `%clang@13.0.0` is setting the compiler, though there is most likely a better way to specify that): 
```
spack:
  packages:
    all:
      providers:
        mpi:
        - mpich
  specs:
  - hepnos@main%clang@13.0.0  cxxstd=14 target=x86_64
  - hepnos-dataloader@0.4    target=x86_64
  - hepnos-pep-benchmark@0.4 target=x86_64
  - mochi-sdskv@main
  - boost cxxstd=17
  - mpich~fortran
  - hwloc
  - hdf5@1.12.1
  concretization: together
  repos:
  - /home/sajid/packages/mochi-spack-packages
  view: true
```
 
 Finally, the compilers definition file:
 ```
 compilers:
- compiler:
    spec: gcc@10.3.0
    paths:
      cc: /usr/bin/gcc-10
      cxx: /usr/bin/g++-10
      f77: /usr/bin/gfortran-10
      fc: /usr/bin/gfortran-10
    flags: {}
    operating_system: ubuntu20.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@9.3.0
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    flags: {}
    operating_system: ubuntu20.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: clang@13.0.0
    paths:
      cc:  /home/sajid/packages/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-10.3.0/llvm-13.0.0-lahl36phwutdnw6zpkdvn26atthydeha/bin/clang
      cxx: /home/sajid/packages/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-10.3.0/llvm-13.0.0-lahl36phwutdnw6zpkdvn26atthydeha/bin/clang++
      f77: /usr/bin/gfortran-10
      fc:  /usr/bin/gfortran-10
    flags:
      cflags: -O2 -march=znver2 -mtune=znver2
      cxxflags: -O2 -march=znver2 -mtune=znver2
      fflags: -O2 -march=znver2 -mtune=znver2
    operating_system: ubuntu20.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
 ```
 
Let me know if I can share any other files. Thanks again!
